//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public int logs_id { get; set; }
        public System.DateTime logs_date { get; set; }
        public System.TimeSpan logs_time { get; set; }
        public string logs_content { get; set; }
    }
}
